import { colornames } from "color-name-list/bestof";

import { hexToOklab } from "../src/lib/color/color";

const entries = colornames.map(({ name, hex }) => ({
  name,
  hex: hex.toUpperCase(),
  oklab: hexToOklab(hex),
}));
const output = `// Generated by scripts/generate-color-catalog.ts from color-name-list Best Of.
// Copyright (c) 2017 David Aerne. Licensed under MIT; see LICENSE-color-name-list.txt.
// Do not edit by hand.
import type { NamedColor } from './color';

export const namedColorCatalog = ${JSON.stringify(entries)} satisfies readonly NamedColor[];
`;

await Bun.write("src/lib/color/catalog.ts", output);
